### ISSUE TITLE
Hangs after joining if mesa on the host is 20.3

### ISSUE THREAD

**Issue by hexchain** [flathub/us.zoom.Zoom#243]
Distro: Arch

After upgrading mesa to 20.3 on the host, Zoom hangs after joining a meeting. It may work once after each reboot but hangs on subsequent runs.

A possibly related stack trace is here, but I doubt if it would be very useful:
```
Thread 49 (LWP 227):
#0  0x00007fce5be6494f in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fce5f7763da in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fce5f778132 in xcb_wait_for_special_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fce481c457e in glPrimitiveBoundingBox () from /usr/lib/x86_64-linux-gnu/GL/default/lib/libGLX_mesa.so.0
#4  0x00007fce481c46e8 in glPrimitiveBoundingBox () from /usr/lib/x86_64-linux-gnu/GL/default/lib/libGLX_mesa.so.0
#5  0x00007fce481c58ae in glPrimitiveBoundingBox () from /usr/lib/x86_64-linux-gnu/GL/default/lib/libGLX_mesa.so.0
#6  0x00007fce481c680c in glPrimitiveBoundingBox () from /usr/lib/x86_64-linux-gnu/GL/default/lib/libGLX_mesa.so.0
#7  0x00007fcdae55a393 in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
#8  0x00007fcdae55c4c4 in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
#9  0x00007fcdae5685bc in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
#10 0x00007fcdae568879 in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
#11 0x00007fcdae55bdf1 in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
#12 0x00007fcdaeab0faa in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
#13 0x00007fce481b92ea in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/libGLX_mesa.so.0
#14 0x00007fce481a6e6f in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/libGLX_mesa.so.0
#15 0x00007fce5999e9ad in ?? () from /usr/lib/x86_64-linux-gnu/libGLX.so.0
#16 0x00007fce5999f3f7 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX.so.0
#17 0x00007fce599a0b08 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX.so.0
#18 0x00007fcdafbf6d3d in QGLXContext::makeCurrent(QPlatformSurface*) () from /app/extra/zoom/xcbglintegrations/libqxcb-glx-integration.so
#19 0x00007fce5ddc5ace in QOpenGLContext::makeCurrent(QSurface*) () from /app/extra/zoom/libQt5Gui.so.5
#20 0x00007fce5ee8c311 in QSGRenderThread::sync(bool) () from /app/extra/zoom/libQt5Quick.so.5
#21 0x00007fce5ee8d6d0 in QSGRenderThread::syncAndRender() () from /app/extra/zoom/libQt5Quick.so.5
#22 0x00007fce5ee9088c in QSGRenderThread::run() () from /app/extra/zoom/libQt5Quick.so.5
#23 0x00007fce5c3de0b3 in QThreadPrivate::start(void*) () from /app/extra/zoom/libQt5Core.so.5
#24 0x00007fce5c2905e2 in ?? () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#25 0x00007fce5be6f473 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6
```

Workarounds:

1. Downgrade mesa on the host back to 20.2.3 (not very desirable, might break other things on the host);
2. Use the freedesktop runtime 20.08 and use the `mesa-git` GL extension from flathub-beta (https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/Mesa-git):

   ```
   $ FLATPAK_GL_DRIVERS=mesa-git flatpak run --runtime-version=20.08 us.zoom.Zoom
   ```

It could possibly be related to https://github.com/flathub/org.libreoffice.LibreOffice/issues/141.

**Comment by physkets** [comment]
I have an AMD processor with integrated graphics, and I'm seeing the same issue.

**Comment by nedrichards** [comment]
The runtime has been upgraded to 20.08 in zoom now but this looks like a mesa bug so following along with a fix upstream would likely be helpful. https://gitlab.freedesktop.org/mesa/mesa/-/issues/3957.

**Comment by hexchain** [comment]
It seems that the 20.08 runtime will have an upgrade with mesa 20.3, so this is a great help. Thanks!
